# Generated by Django 5.0 on 2023-12-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author_article_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Автор'),
        ),
    ]
