# Generated by Django 5.0 on 2023-12-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Список статей', 'verbose_name_plural': 'Список статей'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='pub_date',
        ),
    ]
