# Generated by Django 5.0 on 2024-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_article_options_article_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('last_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['text'], 'verbose_name': 'Список статей', 'verbose_name_plural': 'Список статей'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='articles.author'),
        ),
    ]
