# Generated by Django 5.0 on 2024-01-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_author_alter_article_options_remove_article_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='authors',
        ),
    ]
