# Generated by Django 5.0 on 2024-01-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_rename_content_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.ManyToManyField(related_name='article_comments', to='articles.comment'),
        ),
    ]
