# Generated by Django 5.0 on 2024-01-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_comments_comment_article_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_at',
        ),
    ]
