# Generated by Django 5.0 on 2024-01-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered')], default='INITIAL', max_length=20),
        ),
    ]
