# Generated by Django 5.0 on 2024-01-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderentry',
            options={'verbose_name': 'Добавлено в корзину', 'verbose_name_plural': 'Добавлено в корзину'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='shopping_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_cart', to='shop.order'),
        ),
    ]
