# Generated by Django 5.0 on 2024-01-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentry',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
