# Generated by Django 5.0 on 2024-01-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_options_alter_orderentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AddField(
            model_name='profile',
            name='orders',
            field=models.ManyToManyField(related_name='user_orders', to='shop.order'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
