# Generated by Django 5.0 on 2024-01-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_profile_options_profile_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_entries',
        ),
    ]
